title: Matt Gifford aka coldfumonkeh
author: coldfumonkeh
email: matt@monkehworks.com
my_name: Matt Gifford
my_lead: > 
  Consultant developer, technical author, conference speaker.
description: > # this means to ignore newlines until "show_excerpts:"


show_excerpts: true # set to true to show excerpts on the homepage

markdown: kramdown

date_format: "%b %-d, %Y"

disqus:
  shortname: mattgifford

# generate social links in footer
social_links:
  twitter: coldfumonkeh
  github:  coldfumonkeh
  rss: rss
  youtube: coldfumonkeh
  youtube_channel_name: coldfumonkeh

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  # - about.md

highlighter: rouge

# Build settings

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate

permalink: /:year/:month/:day/:title:output_ext

paginate: 10
paginate_path: "/blog/page:num/"


# custom collections
collections:
  - events